### PR TITLE
12 create discord bot application

### PR DESCRIPTION
**Pull request by maier-s**
Merge current implementation for Bot to main branch.
2 commands implemented:
- $test write the argument back to the user
- $fu answers with "You too!"

Dynamic load of commands are implemented --> Commands get loaded from Com_Bot.py module

### CODE REVIEW

**Comment by maier-s** [comment]
Unit Tests are currently missung

**Comment by maier-s** [comment]
Unit Tests implemented requested review

**Comment by maier-s** [comment]
@d-strobel can we close pull request with this annotation in unit test for LaSaga Bot. Need to fix this issue in another branch, because it will be a seperate iteration. I would focus more in functionallity and develope a solution for the unittesting of coroutines later.

**Review by d-strobel — APPROVED** [review]

**Comment by d-strobel** [comment]
Close or merge ?

**Comment by maier-s** [comment]
> Close or merge ?

Merge

**Pull request merged**
